<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Surefire suite" duration-ms="3713" started-at="2017-03-20T22:51:32Z" finished-at="2017-03-20T22:51:35Z">
    <groups>
      <group name="demo">
        <method signature="PushConfigurationTest.getPushConfiguration()[pri:0, instance:com.eodessa.test.PushConfigurationTest@5b4b6ec8]" name="getPushConfiguration" class="com.eodessa.test.PushConfigurationTest"/>
        <method signature="PushConfigurationTest.validatePathParameter()[pri:0, instance:com.eodessa.test.PushConfigurationTest@5b4b6ec8]" name="validatePathParameter" class="com.eodessa.test.PushConfigurationTest"/>
      </group> <!-- demo -->
    </groups>
    <test name="Surefire test" duration-ms="3713" started-at="2017-03-20T22:51:32Z" finished-at="2017-03-20T22:51:35Z">
      <class name="com.eodessa.test.PushConfigurationTest">
        <test-method status="PASS" signature="configure()[pri:0, instance:com.eodessa.test.PushConfigurationTest@5b4b6ec8]" name="configure" is-config="true" duration-ms="536" started-at="2017-03-20T15:51:31Z" finished-at="2017-03-20T15:51:32Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- configure -->
        <test-method status="PASS" signature="getPushConfiguration()[pri:0, instance:com.eodessa.test.PushConfigurationTest@5b4b6ec8]" name="getPushConfiguration" duration-ms="2124" started-at="2017-03-20T15:51:32Z" finished-at="2017-03-20T15:51:34Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getPushConfiguration -->
        <test-method status="FAIL" signature="validatePathParameter()[pri:0, instance:com.eodessa.test.PushConfigurationTest@5b4b6ec8]" name="validatePathParameter" duration-ms="1569" started-at="2017-03-20T15:51:34Z" finished-at="2017-03-20T15:51:35Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [1] but found [0]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [1] but found [0]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:370)
	at org.testng.Assert.assertEquals(Assert.java:380)
	at com.eodessa.test.PushConfigurationTest.validatePathParameter(PushConfigurationTest.java:62)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:132)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeSingleClass(TestNGDirectoryTestSuite.java:112)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:99)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:147)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validatePathParameter -->
      </class> <!-- com.eodessa.test.PushConfigurationTest -->
    </test> <!-- Surefire test -->
  </suite> <!-- Surefire suite -->
</testng-results>
